# render.yaml
services:
  - type: web
    name: raj-portfolio
    env: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html